version: "{build}"
build: off
shallow_clone: true
skip_tags: true

environment:
  gh_token:
    secure: 2wpMgpk8uexn8fsbGLlwCBWPy9R091m1XmpYNr9Q+SMFsVOYwMTdk242ggjUKa/0
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"
    - nodejs_version: "7"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm -g i npm@latest
  - set PATH=%APPDATA%\npm;%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%
  - npm i --ignore-scripts
  - ps: prebuild -b $(node -v) --strip

test_script:
  - npm test

on_success:
  - ps: appveyor PushArtifact $(dir -name prebuilds\*)
  - ps: if (git describe --exact-match 2>$null) { prebuild -u $env:gh_token }
