version: "{build}"
build: off
shallow_clone: false
skip_tags: true

environment:
  PREBUILD_TOKEN:
    secure: 2wpMgpk8uexn8fsbGLlwCBWPy9R091m1XmpYNr9Q+SMFsVOYwMTdk242ggjUKa/0
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - ps: if ($env:nodejs_version -eq "5") { npm i npm@latest -g }
  - set PATH=%APPDATA%\npm;%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%
  - ps: node-gyp remove $(node -v)
  - npm i --ignore-scripts
  - ps: prebuild -t $(node -v) --strip --verbose

test_script:
  - npm test
