version: "{build}"
build: off
shallow_clone: false
skip_tags: true

environment:
  token:
    secure: 2wpMgpk8uexn8fsbGLlwCBWPy9R091m1XmpYNr9Q+SMFsVOYwMTdk242ggjUKa/0
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"
    - nodejs_version: "7"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm -g i npm@latest
  - set PATH=%APPDATA%\npm;%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%
  - npm i --ignore-scripts
  - for /f %%i in ('node -v') do prebuild -b %%i --strip

test_script:
  - npm test

on_success:
  - for %%i in (prebuilds\*) do appveyor PushArtifact %%i
  - git describe --exact-match 2> nul
  - if %ERRORLEVEL% equ 0 prebuild --upload-all %token%
